/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author komputer
 */
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
public class NewJFrame extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    private JPanel panel;
    private JButton[][] buttons;
    private int emptyX, emptyY;
    private final int SIZE = 4;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initUI();
    }
     private void initUI() {
        panel = new JPanel();
        panel.setLayout(new GridLayout(SIZE, SIZE, 0, 0));
        buttons = new JButton[SIZE][SIZE];
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        BufferedImage img = null;
        try {
            URL imgUrl = new URL("https://picsum.photos/200");
            img = ImageIO.read(imgUrl);
        } catch (IOException e) {
            e.printStackTrace();
     }
        int w = img.getWidth() / SIZE;
        int h = img.getHeight() / SIZE;
        for (int i = 0; i < SIZE; i++) {
            for (int j = 0; j < SIZE; j++) {
                ImageIcon tileIcon = new ImageIcon(img.getSubimage(j * w, i * h, w, h));
                buttons[i][j] = new JButton(tileIcon);
                buttons[i][j].addActionListener((ActionListener) this);
                panel.add(buttons[i][j]);
            }
        }
         buttons[SIZE-1][SIZE-1].setIcon(null);
        emptyX = SIZE-1;
        emptyY = SIZE-1;

   add(panel);
        setTitle("Puzzle Game");
        setSize(new Dimension(img.getWidth(), img.getHeight()));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public void actionPerformed(ActionEvent e) {
        for (int i = 0; i < SIZE; i++) {
            for (int j = 0; j < SIZE; j++) {
                if (e.getSource() == buttons[i][j]) {
                    if ((i == emptyX && Math.abs(j - emptyY) == 1) || 
                        (j == emptyY && Math.abs(i - emptyX) == 1)) {
                        // Swap clicked tile with blank tile
                        ImageIcon tempIcon = (ImageIcon) buttons[i][j].getIcon();
                        buttons[i][j].setIcon(null);
                        buttons[emptyX][emptyY].setIcon(tempIcon);
                        emptyX = i;
                        emptyY = j;
                        return;
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
// Set the Nimbus look and feel 
        SwingUtilities.invokeLater(() -> {
            JFrame game = new JFrame();
            game.setVisible(true);
        });
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
